import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/general/NavBar";
import { AuthProvider } from "@/components/general/AuthProvider";
import MobileNav from "@/components/general/MobileNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <html lang="en">
        <body
          className={`overflow-hidden max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 ${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <NavBar />
          <MobileNav />
          {children}
        </body>
      </html>
    </AuthProvider>
  );
}
